# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: books.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'books.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ooks.proto\x12\x05\x62ooks\"\x11\n\x0fGetBooksRequest\".\n\x10GetBooksResponse\x12\x1a\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0b.books.Book\"@\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\" \n\x12GetBookByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"0\n\x13GetBookByIdResponse\x12\x19\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0b.books.Book\">\n\x0e\x41\x64\x64\x42ookRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x03\";\n\x0f\x41\x64\x64\x42ookResponse\x12(\n\x08response\x18\x01 \x01(\x0b\x32\x16.books.GeneralResponse\"0\n\x0fGeneralResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"\x1f\n\x11\x44\x65leteBookRequest\x12\n\n\x02id\x18\x01 \x01(\x03\">\n\x12\x44\x65leteBookResponse\x12(\n\x08response\x18\x01 \x01(\x0b\x32\x16.books.GeneralResponse\"K\n\x0f\x45\x64itBookRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x03\"<\n\x10\x45\x64itBookResponse\x12(\n\x08response\x18\x01 \x01(\x0b\x32\x16.books.GeneralResponse2\xce\x02\n\x05\x42ooks\x12=\n\x08GetBooks\x12\x16.books.GetBooksRequest\x1a\x17.books.GetBooksResponse\"\x00\x12\x46\n\x0bGetBookById\x12\x19.books.GetBookByIdRequest\x1a\x1a.books.GetBookByIdResponse\"\x00\x12:\n\x07\x41\x64\x64\x42ook\x12\x15.books.AddBookRequest\x1a\x16.books.AddBookResponse\"\x00\x12\x43\n\nDeleteBook\x12\x18.books.DeleteBookRequest\x1a\x19.books.DeleteBookResponse\"\x00\x12=\n\x08\x45\x64itBook\x12\x16.books.EditBookRequest\x1a\x17.books.EditBookResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBOOKSREQUEST']._serialized_start=22
  _globals['_GETBOOKSREQUEST']._serialized_end=39
  _globals['_GETBOOKSRESPONSE']._serialized_start=41
  _globals['_GETBOOKSRESPONSE']._serialized_end=87
  _globals['_BOOK']._serialized_start=89
  _globals['_BOOK']._serialized_end=153
  _globals['_GETBOOKBYIDREQUEST']._serialized_start=155
  _globals['_GETBOOKBYIDREQUEST']._serialized_end=187
  _globals['_GETBOOKBYIDRESPONSE']._serialized_start=189
  _globals['_GETBOOKBYIDRESPONSE']._serialized_end=237
  _globals['_ADDBOOKREQUEST']._serialized_start=239
  _globals['_ADDBOOKREQUEST']._serialized_end=301
  _globals['_ADDBOOKRESPONSE']._serialized_start=303
  _globals['_ADDBOOKRESPONSE']._serialized_end=362
  _globals['_GENERALRESPONSE']._serialized_start=364
  _globals['_GENERALRESPONSE']._serialized_end=412
  _globals['_DELETEBOOKREQUEST']._serialized_start=414
  _globals['_DELETEBOOKREQUEST']._serialized_end=445
  _globals['_DELETEBOOKRESPONSE']._serialized_start=447
  _globals['_DELETEBOOKRESPONSE']._serialized_end=509
  _globals['_EDITBOOKREQUEST']._serialized_start=511
  _globals['_EDITBOOKREQUEST']._serialized_end=586
  _globals['_EDITBOOKRESPONSE']._serialized_start=588
  _globals['_EDITBOOKRESPONSE']._serialized_end=648
  _globals['_BOOKS']._serialized_start=651
  _globals['_BOOKS']._serialized_end=985
# @@protoc_insertion_point(module_scope)
