# Use the official Python 3.11 image as the base image
FROM python:3.11

# Set the working directory within the container
WORKDIR /app

# Copy the necessary files and directories into the container
COPY app.py data/ static/ templates/ requirements.txt /app/

# Upgrade pip and install Python dependencies
RUN python -m pip install --upgrade pip && python -m pip install --no-cache-dir -r requirements.txt

# Expose port 5000 for the Flask application
EXPOSE 5000

# Define the command to run the Flask application using Gunicorn
CMD ["gunicorn", "app:app", "-b", "0.0.0.0:5000", "-w", "4"]